runtime: php72

env_variables:
   APP_KEY: base64:9W/oCFTEYWggU+frooeU8meON1tCM3YmGOCKC2qyR5Q=
   APP_NAME: Asif's WebApp
   APP_ENV: local
   APP_DEBUG: true
   APP_STORAGE: /tmp
   CACHE_DRIVER: database
   SESSION_DRIVER: database
   DB_DATABASE: webappdb
   DB_USERNAME: root
   DB_PASSWORD: webapppw
   DB_SOCKET: "/cloudsql/sharp-ring-319002:asia-south1:webappiid"