runtime: php72

env_variables:
   APP_KEY: base64:qG1BqqSutOCxPRwzCARjRgg/2OCPhYlaax8WQjD9Tlo=
   APP_STORAGE: /tmp
   CACHE_DRIVER: database
   SESSION_DRIVER: database
   DB_DATABASE: webappdb
   DB_USERNAME: root
   DB_PASSWORD: webapppw
   DB_SOCKET: "/cloudsql/sharp-ring-319002:asia-south1:webappiid"